[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^6.21.5
  arduino-libraries/ArduinoMqttClient@^0.1.8
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^3.11.0
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.14
  madhephaestus/ESP32Servo@^3.0.6
